# SPDX-FileCopyrightText: 2025 Jakub Wasylków <kuba_160@protonmail.com>
# SPDX-License-Identifier: CC0-1.0

name: ddb_progress_unity plugin build

on: [push,pull_request]

env:
  ZIG_DOWNLOAD_URL: https://ziglang.org/download/0.15.1/zig-x86_64-linux-0.15.1.tar.xz
  PKG_CONFIG_PATH: ./static-deps/lib-x86-64/lib/pkgconfig
  PKG_CONFIG_DBUS_1_PREFIX: static-deps/lib-x86-64

jobs:
  build_linux:
    name: Linux
    runs-on: ubuntu-latest
    container: ubuntu:20.04

    steps:
    - name: Checkout repository
      uses: actions/checkout@v1
    - name: Install packages
      run: apt-get -qq update && DEBIAN_FRONTEND=noninteractive apt-get install -y -qq curl pkg-config wget xz-utils
    - name: Download Zig 0.15.1
      run: wget --quiet -nc ${ZIG_DOWNLOAD_URL} && tar -xf `basename ${ZIG_DOWNLOAD_URL}`
    - name: Download static deps
      run: mkdir -p temp static-deps && curl -s -L http://sourceforge.net/projects/deadbeef/files/staticdeps/ddb-static-deps-latest.tar.bz2/download -o temp/ddb-static-deps.tar.bz2 && tar jxf temp/ddb-static-deps.tar.bz2 -C static-deps
    - name: Download DeaDBeeF header
      run: wget --quiet -nc https://raw.githubusercontent.com/DeaDBeeF-Player/deadbeef/1.8/deadbeef.h && mkdir -p ./static-deps/lib-x86-64/include/deadbeef && mv deadbeef.h ./static-deps/lib-x86-64/include/deadbeef
    - name: Build ddb_progress_unity
      run: ./`basename ${ZIG_DOWNLOAD_URL} .tar.xz`/zig build --search-prefix static-deps/lib-x86-64 --release
    - name: Upload artifact linux-x86_64.zip
      uses: actions/upload-artifact@v4
      if: ${{ !env.ACT }}
      with:
        name: linux-x86_64
        path: ./zig-out/lib/deadbeef/
